# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbJMuW_MmszHfg5vuZaqvMbd39r58K1j
"""

import streamlit as st
import pandas as pd
import ta
import platform
import matplotlib.pyplot as plt
from datetime import timedelta, datetime
import yfinance as yf
import pmdarima as pm
from statsmodels.tsa.statespace.sarimax import SARIMAX
import numpy as np
import requests
from bs4 import BeautifulSoup
# 注意：確保 stock_eng_to_cn.py 在同一個目錄下，或者註解掉此行
# import stock_eng_to_cn

# ------------------------
# 1. 介面設定與字體處理
# ------------------------
st.set_page_config(page_title="股票時間序列分析", layout="wide")

if platform.system() == "Windows":
    CHINESE_FONT = 'Microsoft JhengHei'
elif platform.system() == "Darwin":  # Mac
    CHINESE_FONT = 'Heiti TC'
else:
    CHINESE_FONT = 'DejaVu Sans'

plt.rcParams['font.sans-serif'] = [CHINESE_FONT]
plt.rcParams['axes.unicode_minus'] = False

# ------------------------
# 2. Sidebar 側邊欄設定
# ------------------------
st.sidebar.title("📊 論文 - 時間序列分析")
st.sidebar.markdown("**G130A007 張嘉娜**")
st.sidebar.markdown("---")

# 初始化 Session State 儲存股票列表
if "stocks" not in st.session_state:
    st.session_state.stocks = [{"sector": "Semiconductors (Tech)", "ticker": "2330.TW"}]

def add_stock():
    st.session_state.stocks.append({"sector": "Semiconductors (Tech)", "ticker": "2330.TW"})

def remove_stock():
    if len(st.session_state.stocks) > 1:
        st.session_state.stocks.pop()

# 資料來源選擇
data_source = st.sidebar.selectbox("📂 資料來源", ["Yahoo Finance", "CSV 上傳"])

# 股票分類資料 (簡化版供示範)
stock_sector_map = {
    "Semiconductors (Tech)": {"2330.TW": "TSMC", "2454.TW": "MediaTek"},
    "AI & Computer Hardware": {"2317.TW": "Hon Hai", "2382.TW": "Quanta"},
    "Financials & Banking": {"2881.TW": "Fubon", "2882.TW": "Cathay"}
}

# 動態生成股票選擇介面
st.sidebar.markdown("### 🏷️ 股票選擇")
selected_tickers = []

for i, s_info in enumerate(st.session_state.stocks):
    with st.sidebar.expander(f"股票 {i+1} 設定", expanded=True):
        if data_source == "Yahoo Finance":
            sector = st.selectbox(f"產業別", list(stock_sector_map.keys()), key=f"sec_{i}")
            ticker = st.selectbox(f"代號", list(stock_sector_map[sector].keys()), key=f"tick_{i}")
            selected_tickers.append(ticker)
        else:
            uploaded_file = st.file_provider(f"上傳 CSV", key=f"file_{i}")
            # CSV 處理邏輯...

col1, col2 = st.sidebar.columns(2)
col1.button("➕ 新增股票", on_click=add_stock)
col2.button("➖ 刪除股票", on_click=remove_stock)

# ------------------------
# 3. 主畫面邏輯
# ------------------------
st.title("📈 股票技術分析與預測系統")

if st.sidebar.button("🚀 開始分析", type="primary"):
    if not selected_tickers:
        st.warning("請至少選擇一支股票")
    else:
        performance_data = {}

        for ticker in selected_tickers:
            st.subheader(f"🔍 分析結果: {ticker}")

            # 獲取資料
            df = yf.download(ticker, start="2023-01-01")
            if df.empty:
                st.error(f"找不到 {ticker} 的資料")
                continue

            # 計算 RSI (使用 ta 套件)
            df['RSI'] = ta.momentum.RSIIndicator(df['Close']).rsi()

            # 簡單 RSI 策略模擬
            df['Signal'] = 0
            df.loc[df['RSI'] < 30, 'Signal'] = 1  # 買入
            df.loc[df['RSI'] > 70, 'Signal'] = -1 # 賣出

            # 累積收益計算 (簡化版)
            df['Returns'] = df['Close'].pct_change()
            df['Strategy_Return'] = df['Signal'].shift(1) * df['Returns']
            df['Cumulative_Return'] = (1 + df['Strategy_Return'].fillna(0)).cumprod()
            df['Buy_Hold_Cumulative'] = (1 + df['Returns'].fillna(0)).cumprod()

            # 繪製圖表
            fig, ax = plt.subplots(figsize=(10, 4))
            ax.plot(df.index, df["Cumulative_Return"], label="RSI 策略", color="blue")
            ax.plot(df.index, df["Buy_Hold_Cumulative"], label="Buy & Hold", color="orange", linestyle="--")
            ax.set_title(f"{ticker} 策略比較")
            ax.legend()
            st.pyplot(fig)

            # 儲存用於多股比較
            performance_data[ticker] = {"df": df.reset_index()}

        # --------------------------
        # 4. 多支股票比較
        # --------------------------
        if len(performance_data) > 1:
            st.markdown("---")
            st.subheader("📊 多支股票 RSI 策略績效比較")

            fig_comp, ax_comp = plt.subplots(figsize=(12, 5))
            for name, data in performance_data.items():
                ax_comp.plot(data["df"]["Date"], data["df"]["Cumulative_Return"], label=f"{name}")

            ax_comp.set_title("RSI 策略累積收益率比較")
            ax_comp.set_ylabel("累積收益率")
            ax_comp.legend()
            st.pyplot(fig_comp)